version: '3.3'
networks:
  mynet:
    driver: overlay
services:
  control:
    hostname: control
    build: ./control
    env_file: ./secret/control.env
    privileged: true
  n1:
    build: ./node
    env_file: ./secret/node.env
    privileged: true
    #container_name: jepsen-n1 # cannot use this - will not scale beyond 1
    hostname: n1
    deploy:
      mode: replicated
      replicas: 2